#!/bin/bash
# ============================================================================
# PJSIP Recompilation Script for Windows with Video Support
# ============================================================================
# This script recompiles PJSIP 2.15.1 with video support enabled
#
# Requirements:
#   - MSYS2 with MinGW-w64 toolchain
#   - FFmpeg already compiled (run build_ffmpeg_windows.sh first)
#   - SDL2 2.28.5 extracted
#   - PJSIP 2.15.1 source at F:/0/pjproject-2.15.1/pjproject-2.15.1
#
# Output:
#   - PJSIP libraries with video support
#   - Copied to project libs/pjsip/
# ============================================================================

set -e  # Exit on error
set -x  # Print commands

echo "========================================"
echo "Rebuilding PJSIP 2.15.1 with Video"
echo "========================================"

# Configuration
PJSIP_SRC=/f/0/pjproject-2.15.1/pjproject-2.15.1
FFMPEG_ROOT=/c/ffmpeg
SDL2_ROOT=/c/video_deps/SDL2-2.28.5
PROJECT_ROOT=/e/2025/3_gongkongji/belt_control_system
JOBS=8

# Check PJSIP source
if [ ! -d "$PJSIP_SRC" ]; then
    echo "ERROR: PJSIP source not found at $PJSIP_SRC"
    echo "Please ensure PJSIP 2.15.1 is extracted there"
    exit 1
fi

# Check FFmpeg
if [ ! -d "$FFMPEG_ROOT" ]; then
    echo "ERROR: FFmpeg not found at $FFMPEG_ROOT"
    echo "Please run build_ffmpeg_windows.sh first"
    exit 1
fi

# Check SDL2
if [ ! -d "$SDL2_ROOT" ]; then
    echo "ERROR: SDL2 not found at $SDL2_ROOT"
    echo "Please run setup_video_dependencies_windows.bat first"
    exit 1
fi

cd "$PJSIP_SRC"

# ============================================================================
# 1. Clean previous build (remove config_site.h first)
# ============================================================================
echo "========================================"
echo "Cleaning previous build..."
echo "========================================"

CONFIG_SITE="${PJSIP_SRC}/pjlib/include/pj/config_site.h"

# Backup and remove existing config_site.h if it exists
if [ -f "$CONFIG_SITE" ]; then
    echo "Backing up existing config_site.h..."
    cp "$CONFIG_SITE" "${CONFIG_SITE}.backup.$(date +%Y%m%d_%H%M%S)"
    rm -f "$CONFIG_SITE"
fi

make distclean 2>/dev/null || true

# ============================================================================
# 2. Configure PJSIP
# ============================================================================
echo "========================================"
echo "Configuring PJSIP..."
echo "========================================"

# Set environment variables for configure
export CFLAGS="-I${FFMPEG_ROOT}/include -I${SDL2_ROOT}/include"
export LDFLAGS="-L${FFMPEG_ROOT}/lib -L${SDL2_ROOT}/lib/x64"
export PKG_CONFIG_PATH="${FFMPEG_ROOT}/lib/pkgconfig"

./configure \
    --enable-video \
    --with-ffmpeg="${FFMPEG_ROOT}" \
    --with-sdl="${SDL2_ROOT}" \
    --disable-libyuv \
    --disable-opencore-amr \
    --disable-silk \
    --disable-opus \
    --disable-speex-aec \
    --disable-g711-codec \
    --disable-g722-codec \
    --disable-g7221-codec

# ============================================================================
# 3. Create/Modify config_site.h (after configure)
# ============================================================================
echo "========================================"
echo "Creating config_site.h with video support..."
echo "========================================"

# Create new config_site.h with video support
cat > "$CONFIG_SITE" << 'EOF'
/*
 * PJSIP Configuration for Video Calling
 * Auto-generated by build_pjsip_windows.sh
 */

/* Enable video support */
#define PJMEDIA_HAS_VIDEO               1

/* FFmpeg video codec */
#define PJMEDIA_HAS_FFMPEG_VID_CODEC    1
#define PJMEDIA_HAS_FFMPEG_CODEC_H264   1

/* SDL video device */
#define PJMEDIA_VIDEO_DEV_HAS_SDL       1
#define PJMEDIA_VIDEO_DEV_HAS_SDL2      1

/* Disable unused audio codecs to save space */
#define PJMEDIA_HAS_SPEEX_CODEC         0
#define PJMEDIA_HAS_GSM_CODEC           0
#define PJMEDIA_HAS_ILBC_CODEC          0

/* Video resolution defaults */
#define PJMEDIA_VID_DEFAULT_WIDTH       640
#define PJMEDIA_VID_DEFAULT_HEIGHT      480
#define PJMEDIA_VID_DEFAULT_FPS         25

/* Performance optimization */
#define PJ_HAS_HIGH_RES_TIMER           1
#define PJMEDIA_USE_OLD_FFMPEG          0

/* Increase max video format */
#define PJMEDIA_VID_DEV_MAX_FORMATS     64
EOF

echo "Created config_site.h with video support"

# ============================================================================
# 4. Build PJSIP
# ============================================================================
echo "========================================"
echo "Building PJSIP..."
echo "========================================"
echo "This may take 15-30 minutes..."

make dep
make -j${JOBS}

# ============================================================================
# 5. Verify build
# ============================================================================
echo "========================================"
echo "Verifying PJSIP build..."
echo "========================================"

# Check if video device library was built
VIDEODEV_LIB=$(find lib -name "*pjmedia-videodev*.a" 2>/dev/null | head -1)
if [ -z "$VIDEODEV_LIB" ]; then
    echo "ERROR: pjmedia-videodev library not found"
    echo "Video support was not enabled properly"
    exit 1
fi

echo "[OK] Found video device library: $VIDEODEV_LIB"

# List all built libraries
echo ""
echo "Built libraries:"
ls -lh lib/*.a | grep -E "(pjmedia|pjsua)" || ls -lh lib/*.a

# ============================================================================
# 6. Copy libraries to project
# ============================================================================
echo ""
echo "========================================"
echo "Copying libraries to project..."
echo "========================================"

PROJECT_LIBS="${PROJECT_ROOT}/libs/pjsip"
if [ ! -d "$PROJECT_LIBS" ]; then
    mkdir -p "$PROJECT_LIBS"
fi

# Copy all PJSIP libraries
cp -v lib/*.a "$PROJECT_LIBS/"

echo ""
echo "Libraries copied to: $PROJECT_LIBS"
ls -lh "$PROJECT_LIBS" | wc -l
echo " library files copied"

# ============================================================================
# 7. Test video support (optional)
# ============================================================================
echo ""
echo "========================================"
echo "Testing video support..."
echo "========================================"

PJSUA_BIN=$(find . -name "pjsua-*" -type f 2>/dev/null | head -1)
if [ -n "$PJSUA_BIN" ] && [ -x "$PJSUA_BIN" ]; then
    echo "Testing pjsua with --video flag..."
    $PJSUA_BIN --help | grep -i video && echo "[OK] Video option available" || echo "[WARNING] Video option not found in help"
else
    echo "[WARNING] pjsua binary not found, skipping runtime test"
fi

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "========================================"
echo "PJSIP Build Complete"
echo "========================================"
echo "PJSIP source: $PJSIP_SRC"
echo "Video device library: $VIDEODEV_LIB"
echo "Libraries copied to: $PROJECT_LIBS"
echo ""
echo "Next steps:"
echo "1. Update project CMakeLists.txt to link pjmedia-videodev"
echo "2. Add FFmpeg and SDL2 libraries to CMakeLists.txt"
echo "3. Remove stub file: src/risip/pjsip_stub/pjmedia_vid_dev_stub.c"
echo "4. Implement VideoCallManager C++ class"
echo ""
echo "See VIDEO_RESEARCH_SUMMARY.md for detailed CMakeLists.txt changes"
echo "========================================"
