### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Pidai1)
add_subdirectory(Pidai1Content)
add_subdirectory(App)
add_subdirectory(Generated)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Pidai1plugin
    Pidai1Contentplugin
    Generated_QtQuick3D_皮带机8plugin
    Generated_QtQuick3D_PD8plugin
    QtQuickDesignerComponents)